### ISSUE TITLE
app=attack level=ERROR msg=Unhandled exception

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act#1]
Hi, I'm installing ACT on CentOS 7 with your Installation Guide step by step.
1. Requirements (DONE)
2. Core platform (DONE)
3. Data model (DONE)
4. GUI (DONE)
5. Workers (Error)
6. Scio (Not yet)

Now I'm at "**5. Workers**".
After running below command as act user, error occured.
`act-attack --act-baseurl http://localhost:8888 --user-id 1`

Error messages are followings:
[2019-05-26 01:49:35] app=attack level=ERROR msg=Unhandled exception: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 404, in main_log_error
    main()
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 383, in main
    groups_notify = add_groups(actapi, attack, args.output_format)
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 178, in add_groups
    handle_fact(fact, output_format=output_format)
  File "/usr/lib/python3.6/site-packages/act/api/helpers.py", line 37, in handle_fact
    fact.add()
  File "/usr/lib/python3.6/site-packages/act/api/fact.py", line 390, in add
    return self.__add_fact()
  File "/usr/lib/python3.6/site-packages/act/api/fact.py", line 411, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 194, in api_request
    **kwargs
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 62, in request
    raise ResponseError(res.text)
act.api.base.ResponseError: {"responseCode":412,"limit":0,"count":0,"messages":[{"type":"FieldError","message":"ObjectType does not exist.","messageTemplate":"object.type.not.exist","field":"objectType","parameter":"event","timestamp":"2019-05-25T16:49:35.071Z"}],"data":null,"size":0}

Traceback (most recent call last):
  File "/usr/bin/act-attack", line 11, in <module>
    load_entry_point('act-workers==0.7.0', 'console_scripts', 'act-attack')()
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 404, in main_log_error
    main()
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 383, in main
    groups_notify = add_groups(actapi, attack, args.output_format)
  File "/usr/lib/python3.6/site-packages/act/workers/attack.py", line 178, in add_groups
    handle_fact(fact, output_format=output_format)
  File "/usr/lib/python3.6/site-packages/act/api/helpers.py", line 37, in handle_fact
    fact.add()
  File "/usr/lib/python3.6/site-packages/act/api/fact.py", line 390, in add
    return self.__add_fact()
  File "/usr/lib/python3.6/site-packages/act/api/fact.py", line 411, in __add_fact
    fact = self.api_post("v1/fact", **params)["data"]
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 202, in api_post
    return self.api_request("POST", uri, json=kwargs)
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 194, in api_request
    **kwargs
  File "/usr/lib/python3.6/site-packages/act/api/base.py", line 62, in request
    raise ResponseError(res.text)
act.api.base.ResponseError: {"responseCode":412,"limit":0,"count":0,"messages":[{"type":"FieldError","message":"ObjectType does not exist.","messageTemplate":"object.type.not.exist","field":"objectType","parameter":"event","timestamp":"2019-05-25T16:49:35.071Z"}],"data":null,"size":0}
[act@act act-frontend]$ 

![ACT_act-attack_20190526](https://user-images.githubusercontent.com/10558255/58372576-4dc43800-7f5a-11e9-9622-a5932278f746.png)

Could you give me some advices to fix the issue.

Many thanks,
Yuki

**Comment by frbor** [comment]
Hi Yuki,

It's great that you could test the new documentation.

Unfortunately it looks like the latest data model (`act-types`) was not published on pypi. I have published it now, and you should be able to do:

```
pip3 install --upgrade act-types
```

This should give you version `0.7.0`.

Afterwards you could run this again:

```
act-types \
    --userid 1 \
    --act-baseurl http://localhost:8888 \
    --default-object-types \
    --default-fact-types \
    --default-meta-fact-types \
    add
```

This might leave some unused fact types, but for testing it should not be any problems. However, if you would like to remove the old fact types first, you can run this, _before_ you run act-types again:

```
sudo -u act sh -c "cqlsh -f ~/src/act-platform/dao/testsrc/resources/setup.cql"
curl -XDELETE 'http://localhost:9200/act?pretty'
sudo service act-app restart
```

Please note, the above statement will drop all types and data that you have in the platform, but in your case that would be intentional.

**Comment by nakagit** [comment]
Hi frbor,

Thanks for your help, I could get over the previous issue.

Current Status is here:
1. Requirements (DONE)
2. Core platform (DONE)
3. Data model (DONE)
4. GUI (DONE)
5. Workers (DONE)
6. Scio (DONE)

But, I encountered the following error: (See screenshot)
`JSON parse: unexpected character at line 1 column 1 of the JSON data.
`
Any ideas to fix?
![ACT_GUI_Error](https://user-images.githubusercontent.com/10558255/59964413-3a958f80-953b-11e9-893d-80b9be1b5ee8.png)

Kind regards,
Yuki

**Comment by frbor** [comment]
Hi Yuki - it is not that easy to see from your screenshot, but it looks like the GUI are having problems connecting to the backend (it says "Error loading required data" in the upper left corner). 

Are you running the backend through nginx or another proxy? If not you might need to adjust src/config.js in act-front to point to "http://localhost:8888" and change the CORS settings in the platform.

**Comment by frbor** [comment]
Is this still an issue? If not, I will close this issue.
